### PR TITLE
remove ipad default

### PR DESCRIPTION
**Pull request by wmill**
The ipad rtl landscape setting is causing me problems.  Could you remove it or make it configureable?

### CODE REVIEW

**Comment by davidhantson** [comment]
I just got a bug report for my project telling me that te text is in reverse on an iPad mini. Why on earth would the direction be rtl on an iPad by default??? It's even in the "tests.css" file , can we please remove this default or make it at least configurable?

**Comment by olivierbossel** [comment]
Hi guys,
The code you talk about is part of the demo. The _grid-settings.scss file here is just the configuation for the demo so you can totally adapt this code to suit your needs...

**Comment by wmill** [comment]
The issue is that it's included in the npm module, and you shouldn't need to edit files in the npm module.

**Comment by olivierbossel** [comment]
Yes I know that's it's included in the npm module. But all the code in the demo folder it just for demo purpose and you don't have to rely on these files at all in your codebase.
You'll have to create your own files in your project like:
- _grid-settings.scss : import gridle + register your own states, etc...
- _grid.scss : import _grid-settings.scss and generate your classes using `g-classes()` mixin
- _style.scss (or whatever you want your file to be names) : import _grid-settings.scss + your project css
I can and I certainly going to add a line in the `scripts/install.sh` script that will delete the demo folder when the npm module is installed so it will not be so confusing...
Hope I correctly understand your issue, otherwise let me know :)
Thanks for your feedback by the way, appreciate that!
Cheers!

**Pull request closed without merging**
